repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: black
        language: python
        entry: python -m black
        types: [python]
