name: Try in Web IDE example
on:
  pull_request_target:
    # Triggers workflow on pull request open
    types: [opened, reopened, synchronize]
jobs:
  add-link:
    runs-on: ubuntu-20.04
    steps:
      - name: Web IDE Pull Request Check
        id: try-in-web-ide
        uses: redhat-actions/try-in-web-ide@v1
        with:
          # GitHub action inputs
          # required
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optional - defaults to true
          add_comment: true
          # optional - defaults to true
          add_status: true
          # optional - Redirect to IBM Bluemix Cluster
          web_ide_instance: https://codeready-codeready-workspaces.csd-k8s-demo-0cc5678638ed51c2a34ed6691df3acb6-0000.us-south.containers.appdomain.cloud/
          # optional - Vanity
          comment_badge: https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20JCH-2F8CD16?logo=eclipse-che&labelColor=FE193E
