name: S2I build and push
on: [ push, workflow_dispatch, pull_request ]
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  APP_NAME: petclinic
  IMAGE_TAGS: latest ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    name: Build and push to ghcr.io
    steps:
      # Checkout spring petclinic repository
      - name: Checkout
        uses: actions/checkout@v2
      # Setup S2I and build container image
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          builder_image: 'docker.io/centos/python-38-centos7:1'
      # Push image to the GitHub container registry
      - name: Push To GitHub container registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
